/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ClaudeCodeRouteImport } from './routes/claude-code'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TricksAndTipsIndexRouteImport } from './routes/tricks-and-tips/index'
import { Route as TranscriptsIndexRouteImport } from './routes/transcripts/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PlansIndexRouteImport } from './routes/plans/index'
import { Route as FilesIndexRouteImport } from './routes/files/index'
import { Route as SettingsProjectIdRouteImport } from './routes/settings/$projectId'
import { Route as PlansPlanIdRouteImport } from './routes/plans/$planId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as TranscriptsProjectIdIndexRouteImport } from './routes/transcripts/$projectId/index'
import { Route as FilesSessionIdIndexRouteImport } from './routes/files/$sessionId/index'
import { Route as TranscriptsProjectIdSessionIdRouteImport } from './routes/transcripts/$projectId/$sessionId'
import { Route as FilesSessionIdFileHashRouteImport } from './routes/files/$sessionId/$fileHash'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeCodeRoute = ClaudeCodeRouteImport.update({
  id: '/claude-code',
  path: '/claude-code',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TricksAndTipsIndexRoute = TricksAndTipsIndexRouteImport.update({
  id: '/tricks-and-tips/',
  path: '/tricks-and-tips/',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptsIndexRoute = TranscriptsIndexRouteImport.update({
  id: '/transcripts/',
  path: '/transcripts/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProjectIdRoute = SettingsProjectIdRouteImport.update({
  id: '/settings/$projectId',
  path: '/settings/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptsProjectIdIndexRoute =
  TranscriptsProjectIdIndexRouteImport.update({
    id: '/transcripts/$projectId/',
    path: '/transcripts/$projectId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FilesSessionIdIndexRoute = FilesSessionIdIndexRouteImport.update({
  id: '/files/$sessionId/',
  path: '/files/$sessionId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptsProjectIdSessionIdRoute =
  TranscriptsProjectIdSessionIdRouteImport.update({
    id: '/transcripts/$projectId/$sessionId',
    path: '/transcripts/$projectId/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FilesSessionIdFileHashRoute = FilesSessionIdFileHashRouteImport.update({
  id: '/files/$sessionId/$fileHash',
  path: '/files/$sessionId/$fileHash',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/claude-code': typeof ClaudeCodeRoute
  '/history': typeof HistoryRoute
  '/mcp': typeof McpRoute
  '/skills': typeof SkillsRoute
  '/api/chat': typeof ApiChatRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/settings/$projectId': typeof SettingsProjectIdRoute
  '/files': typeof FilesIndexRoute
  '/plans': typeof PlansIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/transcripts': typeof TranscriptsIndexRoute
  '/tricks-and-tips': typeof TricksAndTipsIndexRoute
  '/files/$sessionId/$fileHash': typeof FilesSessionIdFileHashRoute
  '/transcripts/$projectId/$sessionId': typeof TranscriptsProjectIdSessionIdRoute
  '/files/$sessionId': typeof FilesSessionIdIndexRoute
  '/transcripts/$projectId': typeof TranscriptsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/claude-code': typeof ClaudeCodeRoute
  '/history': typeof HistoryRoute
  '/mcp': typeof McpRoute
  '/skills': typeof SkillsRoute
  '/api/chat': typeof ApiChatRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/settings/$projectId': typeof SettingsProjectIdRoute
  '/files': typeof FilesIndexRoute
  '/plans': typeof PlansIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/transcripts': typeof TranscriptsIndexRoute
  '/tricks-and-tips': typeof TricksAndTipsIndexRoute
  '/files/$sessionId/$fileHash': typeof FilesSessionIdFileHashRoute
  '/transcripts/$projectId/$sessionId': typeof TranscriptsProjectIdSessionIdRoute
  '/files/$sessionId': typeof FilesSessionIdIndexRoute
  '/transcripts/$projectId': typeof TranscriptsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/claude-code': typeof ClaudeCodeRoute
  '/history': typeof HistoryRoute
  '/mcp': typeof McpRoute
  '/skills': typeof SkillsRoute
  '/api/chat': typeof ApiChatRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/settings/$projectId': typeof SettingsProjectIdRoute
  '/files/': typeof FilesIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/transcripts/': typeof TranscriptsIndexRoute
  '/tricks-and-tips/': typeof TricksAndTipsIndexRoute
  '/files/$sessionId/$fileHash': typeof FilesSessionIdFileHashRoute
  '/transcripts/$projectId/$sessionId': typeof TranscriptsProjectIdSessionIdRoute
  '/files/$sessionId/': typeof FilesSessionIdIndexRoute
  '/transcripts/$projectId/': typeof TranscriptsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/claude-code'
    | '/history'
    | '/mcp'
    | '/skills'
    | '/api/chat'
    | '/plans/$planId'
    | '/settings/$projectId'
    | '/files'
    | '/plans'
    | '/settings'
    | '/transcripts'
    | '/tricks-and-tips'
    | '/files/$sessionId/$fileHash'
    | '/transcripts/$projectId/$sessionId'
    | '/files/$sessionId'
    | '/transcripts/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/claude-code'
    | '/history'
    | '/mcp'
    | '/skills'
    | '/api/chat'
    | '/plans/$planId'
    | '/settings/$projectId'
    | '/files'
    | '/plans'
    | '/settings'
    | '/transcripts'
    | '/tricks-and-tips'
    | '/files/$sessionId/$fileHash'
    | '/transcripts/$projectId/$sessionId'
    | '/files/$sessionId'
    | '/transcripts/$projectId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/claude-code'
    | '/history'
    | '/mcp'
    | '/skills'
    | '/api/chat'
    | '/plans/$planId'
    | '/settings/$projectId'
    | '/files/'
    | '/plans/'
    | '/settings/'
    | '/transcripts/'
    | '/tricks-and-tips/'
    | '/files/$sessionId/$fileHash'
    | '/transcripts/$projectId/$sessionId'
    | '/files/$sessionId/'
    | '/transcripts/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ClaudeCodeRoute: typeof ClaudeCodeRoute
  HistoryRoute: typeof HistoryRoute
  McpRoute: typeof McpRoute
  SkillsRoute: typeof SkillsRoute
  ApiChatRoute: typeof ApiChatRoute
  PlansPlanIdRoute: typeof PlansPlanIdRoute
  SettingsProjectIdRoute: typeof SettingsProjectIdRoute
  FilesIndexRoute: typeof FilesIndexRoute
  PlansIndexRoute: typeof PlansIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TranscriptsIndexRoute: typeof TranscriptsIndexRoute
  TricksAndTipsIndexRoute: typeof TricksAndTipsIndexRoute
  FilesSessionIdFileHashRoute: typeof FilesSessionIdFileHashRoute
  TranscriptsProjectIdSessionIdRoute: typeof TranscriptsProjectIdSessionIdRoute
  FilesSessionIdIndexRoute: typeof FilesSessionIdIndexRoute
  TranscriptsProjectIdIndexRoute: typeof TranscriptsProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude-code': {
      id: '/claude-code'
      path: '/claude-code'
      fullPath: '/claude-code'
      preLoaderRoute: typeof ClaudeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tricks-and-tips/': {
      id: '/tricks-and-tips/'
      path: '/tricks-and-tips'
      fullPath: '/tricks-and-tips'
      preLoaderRoute: typeof TricksAndTipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcripts/': {
      id: '/transcripts/'
      path: '/transcripts'
      fullPath: '/transcripts'
      preLoaderRoute: typeof TranscriptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/': {
      id: '/files/'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$projectId': {
      id: '/settings/$projectId'
      path: '/settings/$projectId'
      fullPath: '/settings/$projectId'
      preLoaderRoute: typeof SettingsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcripts/$projectId/': {
      id: '/transcripts/$projectId/'
      path: '/transcripts/$projectId'
      fullPath: '/transcripts/$projectId'
      preLoaderRoute: typeof TranscriptsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/$sessionId/': {
      id: '/files/$sessionId/'
      path: '/files/$sessionId'
      fullPath: '/files/$sessionId'
      preLoaderRoute: typeof FilesSessionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcripts/$projectId/$sessionId': {
      id: '/transcripts/$projectId/$sessionId'
      path: '/transcripts/$projectId/$sessionId'
      fullPath: '/transcripts/$projectId/$sessionId'
      preLoaderRoute: typeof TranscriptsProjectIdSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/$sessionId/$fileHash': {
      id: '/files/$sessionId/$fileHash'
      path: '/files/$sessionId/$fileHash'
      fullPath: '/files/$sessionId/$fileHash'
      preLoaderRoute: typeof FilesSessionIdFileHashRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ClaudeCodeRoute: ClaudeCodeRoute,
  HistoryRoute: HistoryRoute,
  McpRoute: McpRoute,
  SkillsRoute: SkillsRoute,
  ApiChatRoute: ApiChatRoute,
  PlansPlanIdRoute: PlansPlanIdRoute,
  SettingsProjectIdRoute: SettingsProjectIdRoute,
  FilesIndexRoute: FilesIndexRoute,
  PlansIndexRoute: PlansIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TranscriptsIndexRoute: TranscriptsIndexRoute,
  TricksAndTipsIndexRoute: TricksAndTipsIndexRoute,
  FilesSessionIdFileHashRoute: FilesSessionIdFileHashRoute,
  TranscriptsProjectIdSessionIdRoute: TranscriptsProjectIdSessionIdRoute,
  FilesSessionIdIndexRoute: FilesSessionIdIndexRoute,
  TranscriptsProjectIdIndexRoute: TranscriptsProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
